canonical/server-jenkins-jobs

git-ubuntu/jobs-ci.yaml

The two sources for snapcraft differ on behaviour and release
management. We're having trouble aligning our CI with "official" builds
on Launchpad. We've been advised to try the edge snap which has some
non-determinism removed. And we're told that Launchpad is expected to
switch to the snap eventually. So tweak our CI accordingly.

Switch to using the snapcraft snap over the deb

---

simplestreams/jobs.yaml
simplestreams/parameters.yaml

Simplestreams has moved from bzr to git, and bzr will stop working
shortly. [1]
It also changes the tests to run in an lxc (bionic) container via
utilization of 'ctool' which was added today to uss-tableflip.
Hopefully running in a container will fix the errors we've been
seeing lately around gpg:
gpg: can't connect to the agent: IPC connect call failed
gpg: error getting the KEK: No agent running
[1] https://code.launchpad.net/~smoser/simplestreams/trunk.moved-to-git/+merge/348547

simplestreams: Move to using git and run tox in a container.

---

simplestreams/jobs-ci.yaml

This just makes the simplestreams c-i review tool use ctool as
we had done with the trunk tests.  We need to do that for the same reason
as the previous... to avoid gpg agent issues
gpg: can't connect to the agent: IPC connect call failed

simplestreams: use ctool for c-i review.

---

simplestreams/jobs-ci.yaml

tox_parameters variable was not set, as it is not a parameter
of the job.  So just remove it from the ctool invocation.
Also do not run with 'set -u'.  That just seems pedantic here.

simplestreams-ci: fixed use of unused variable.

---

curtin/jobs-vmtest-daily.yaml

These options will enable the taring up of disks and keeping them around when a specific test fails. This was requested by @raharper for a temporary test.

curtin: temporarily enable keep_data_fail and tar

---

metrics/metrics.yaml

This depends on https://github.com/CanonicalLtd/metrics/pull/7

Switching metrics/cloud_images to InfluxDB

---

cloud-init/integration-nocloudkvm.yaml
cloud-init/integration-proposed.yaml

The jenkins slave 'torkoal' has a tmpdir set up on top of an nvme disk at
/var/lib/jenkins/tmp.  This change will make the nocloud tests use
that for their TMPDIR.  The hope is that this will fix some timeouts
we were seeing in nocloud-kvm tests where the system simply was taking
longer than allowed to boot.
Note that TMPDIR is documented (and tested locally) as passing
through tox without a 'passenv'.

torkoal: set TMPDIR in cloud-init nocloud-kvm tests to use nvme drive.

---

cloud-init/integration-ec2.yaml
cloud-init/integration-lxd.yaml
cloud-init/integration-nocloudkvm.yaml

When running integration tests, we should match the version of the
test-harness with the version of the deb we're running.  Otherwise
we will get skew and have test failures when a test makes an assertion
that is not availble in the installed package or vice-versa.
The fix here pulls the hash out of the daily deb file name.
cloud-init_18.4-1964-g9f88125-0ubuntu1+1635~trunk~ubuntu18.04.1_all.deb
It grabs the -g9f88125 there and then checks out cloud-init at gf88125.

cloud-init: Match test harness version and daily deb version.

---

curtin/jobs-vmtest.yaml

We want to only test ubuntu for our proposed testing.  Add a new
parameter to the proposed test and set the default value to
target_distro=ubuntu.  This allows users to customize the job
later so add additional (or remove) the filter as well.

curtin: Add a vmtest_filters parameter for proposed testing default to ubuntu only

---

simplestreams/jobs.yaml

When building source, we dont need all the depends.
Also run with 'set -e' so that if the bddeb fails we do not go on
and try to sbuild with a non-existing file *.dsc.

simplestreams-build: invoke build-deb -S also with -d (ignore depends).

---

cloud-init/centos.yaml

Another step towards fixing `cloud-init-copr-build`.

cloud-init: set http_proxy and https_proxy before calling run-centos

---

cloud-init/centos.yaml
cloud-init/default.yaml

Don't build on epel-6 and set http_proxy to access the CentOS repos and Copr from torkoal.

Fix the Copr build/test job

---

metrics/metrics.yaml

Setup long ago at an attempt to collect metrics from it, but not doing
anything useful.

Remove the metric-server-google-analytics job

---

cloud-init/jobs-ci.yaml

In a case where change A and B cause each other to fail, but neither are
failing in isolation, running the autolander for A and B in parallel
will cause master to be broken after both complete.
(Per https://stackoverflow.com/a/48768101, this is how to disable
concurrent pipeline jobs.)

cloud-init: disable concurrent autoland builds

---

metrics/default.yaml
metrics/metrics.yaml

Staging isn't retracing crashes regularly so the retracer results job was failing regularly because there was no data. Subsequently, we'll drop that job for now.
I've also added in a job for the retracers average processing time metric.

Disable staging retracer results, add in production retracer avg time

---

cloud-init/jobs-ci.yaml
curtin/jobs-ci.yaml
simplestreams/jobs-ci.yaml

These run in a predictable amount of time, so if they're taking more
than 15 minutes then we've almost certainly hit some sort of issue.

add timeout to cloud-init,curtin,simplestreams trigger jobs

---

curtin/default.yaml
curtin/jobs-vmtest-daily.yaml
curtin/jobs-vmtest-proposed.yaml
curtin/jobs-vmtest.yaml

Curtin vmtest load is high and current runs take about 14 hours.
This branch does:
- Add disco to daily and -proposed
- Daily drops trusty, adds bionic, reschedules to 4 UTC, xenial
on days 1,3,5, and bionic on days 2, 4, 6.
- Proposed splits up xenial -> disco over different days.
- Start vmtest-devel-amd64-proposed a bit later.

curtin: reschedule vmtests add disco

---

curtin/default.yaml
curtin/jobs-vmtest-proposed.yaml

- Add eoan to -proposed
- Reschedule the vmtest-proposed jobs so that they run twice per week
for LTS releases and once per week for non-LTS releases.

curtin: add eoan

---

admin/admin-master-enable.yaml

Download jenkins-cli.jar from http://server-team-jenkins-be.internal:8080
instead of using jenkins.ubuntu.com, which at the moment can't be
reached from the Internet per (temporary?) IS policy.

admin-master-enable: use server-team-jenkins-be.internal

---

cloud-init/default.yaml
cloud-init/integration-proposed.yaml

Jenkins *proposed jobs are long-running and frequently get hit by intermittent errors in either lxd (teardown) or kvm (gpg key/timeout errors). Decoupling these tests from one another based on platform will hopefully give us a chance to see green in one platform at at time and avoid having to re-run a two hour test.

cloud-init: separate proposed platform jobs

---

daily-triage/cloud-init-curtin-email.sh

We don't want to reply to the From address (server@jenkins.canonical.com).

curtin/cloud-init triage email: set Reply-To header

---

cloud-init/centos.yaml

And execute script in xtrace mode (set -x).

cloud-init copr build: use longer retry intervals

---

pycloudlib/jobs-ci.yaml

Launchpad can't be reached via squid.internal.

pycloudlib ci: exempt .launchpad.net from https proxying

---

.travis.yml

Now that torkoal has been redeployed with Bionic we can use the
jenkins-job-builder Ubuntu package insead of installing from PyPI.
Let's make Travis run the tests with the same version we're going to
use from now on.

travis: use JJB 2.0.3 (the version in Bionic)

---

admin/deploy.yaml

force_update is a parameter, i.e. an environment variable.
It doesn't have to be set from a Jenkins variable.

admin-jobs-update: fix the force_update parameter

---

cloud-init/jobs-ci.yaml
curtin/jobs-ci.yaml
simplestreams/jobs-ci.yaml

The JJB default is to take no action if the timeout is reached; the
action has to be set explicitly.

explicitly set 'fail: true' in the timeout wrappers

---

daily-triage/cloud-init-curtin-sstreams-email.sh
daily-triage/daily-triage.yaml
daily-triage/default.yaml

Changes:
- Cleanup the workspace before each run
- On failures email the QA engineer only
- Add simplestreams

daily-triage email: add simplestreams

---

cloud-init/integration-nocloudkvm.yaml

Parameters become environment variables exported in all the build stages.

No need to pass parameter variables

---

git-ubuntu/jobs-ci.yaml

Apparently in newer Jenkins versions variables set with single quotes
are not expanded anymore. Switch to double quotes.

git-ubuntu-ci: use double quotes when setting VM_NAME

---

admin/admin-git.yaml
cloud-init/jobs-ci.yaml
curtin/jobs-ci.yaml
git-ubuntu/jobs-ci.yaml
simplestreams/jobs-ci.yaml

Deprecated parameters:
- `launchpadTrigger --repo-type` (only Git is supported)
- `admin/admin-git.yaml --branch`

JLP: preserve the launchpadTrigger RC; drop deprecated parameters

---

cloud-init/jobs-ci.yaml
git-ubuntu/jobs-ci.yaml

Run the CI jobs on any metal-amd64 node instead of forcing the jobs to
run on torkoal.

Run the CI jobs on any metal-amd64 node

---

curtin/jobs-ci.yaml
curtin/parameters.yaml

When manually adding a branch for CI, make it easier to know what values to put in which input.

curtin-ci: update param descriptions, order to match cloud-init-ci

---

daily-triage/daily-triage.yaml

All the nodes should now be able to run this job. The job will now run
on any node setup with "Use this node as much as possible", which we
normally reserve for the metal-amd64 nodes.

Run the table-flip daily triage job on any node

---

simplestreams/jobs.yaml

Other changes:
- replace 'rm -rf' with the workspace-cleanup wrapper
- timestamp the build
- run with stricter bash flags

simplestreams-tests: ensure to cleanup the container after building

---

curtin/jobs-ci.yaml

The --skip-images-dirlock gives jenkins-runner more priority over
vmtest-sync-images, allowing the curtin-ci job to run immediately
even if a vmtest-sync-images process is waiting.
The jenkins-runner will still wait if vmtest-sync-images is actually
updateing the images, and not just waiting for its turn.

curtin-ci: run jenkins-runner with --skip-images-dirlock

---

curtin/jobs-ci.yaml

Same as db8131c1dcf1734dbb7b324cf884fe458b90138c but for curtin-autoland-test.

curtin-autoland-test: run jenkins-runner with --skip-images-dirlock

---

curtin/default.yaml
curtin/jobs-vmtest-daily.yaml
curtin/jobs-vmtest-proposed.yaml
curtin/jobs-vmtest.yaml

The builder is run before each vmtest run, checks if the images have been
updated recently enough and runs vmtest-sync-images if necessary. This
will update the images on any node the vmtests are run on.
The builder is not run as part of the curtin-ci job, as we want it to
run as soon as possible, with the existing images.

Replace the curtin-vmtest-sync-images job with a builder

---

curtin/default.yaml
curtin/jobs-ci.yaml
curtin/jobs-vmtest-daily.yaml
curtin/jobs-vmtest-proposed.yaml
curtin/jobs-vmtest.yaml
curtin/jobs.yaml
curtin/parameters.yaml

- Replace the `rm -rf` commands with the workspace-cleanup wrapper.
- Use the timestamps wrapper in the longer vmtest jobs.
- Make the vmtest builder names more uniform. The vmtest jobs now all
begin with 'curtin-vmtest-*', while the builders are called
vmtest-{devel,daily,proposed}.
- Minor cosmetic changes.

curtin: use the timestamps and workspace-cleanup wrappers

---

cloud-init/default.yaml
cloud-init/integration-nocloudkvm.yaml
cloud-init/jobs-ci.yaml

When we have the failure to ssh issue, it's not possible to debug this from what's currently collected.  This is an attempt to archive all of the output on failure such that we can work out why things failed. 
Local results dir for a successful run come in at 2G per dir.  So this may be too much space.  Interested in discussing other ways to capture the qcow snapshot when we fail to ssh connect.
Also, not sure if this achieves my desired goal, so looking for feedback on change independent of whether it's a good idea long term.

On failure, archive all the things

---

curtin/jobs-ci.yaml

This makes the job less prone to fail in case of network hiccups.

curtin-ci: retry git clone and fetch a few times

---

metrics/metrics.yaml

The commands are retried 4 times over about 13 minutes with cubic backoff.

metrics: retry the commands accessing the network a few times

---

cloud-init/other.yaml

Currently jenkins mirrors cloud-init from launchpad's git repo into github.
This change has jenkins mirror FROM github TO launchpad.
I've tested each script line (with the exception of the final git push --mirror to launchpad) on our jenkins master.
Any gotchas we should be worried about?

mirror: git sync from github and mirror to launchpad

---

curtin/jobs-vmtest.yaml
curtin/parameters.yaml

Changes:
- vmtest-add-repos: skip the intermediate vmtest_add_repos variable
- Set the vmtest-add-repos parameter default from a variable
- Add the curtin-cloudinit-sru job

Refactor the vmtest parameters and add the curtin-cloudinit-sru job

---

cloud-init/other.yaml

Launchpad is not unreachable via squid.internal.

cloud-init-style-tip: export no_proxy=launchpad.net

---

cloud-init/default.yaml
curtin/default.yaml
curtin/jobs-vmtest-daily.yaml
curtin/jobs-vmtest-proposed.yaml
curtin/jobs-vmtest.yaml

Set the default number of stored builds to 3 and remove all the
job-specific num-to-keep settings. We'll turn the knob up for specific
jobs if needed.
Fixes #99.

curtin/cloud-init: reduce the number of stored builds

---

cloud-init/default.yaml
cloud-init/integration-ec2.yaml
cloud-init/integration-lxd.yaml
cloud-init/integration-nocloudkvm.yaml

Do not add '-proposed' jobs yet because we won't yet be using the -proposed suites for Focal until it officially releases

cloud-init: add focal to ci

---

curtin/default.yaml
curtin/jobs-vmtest-daily.yaml

change daily scheduling of b and x, reducing frequency of each daily run to 1 series per day.
Alternate(stripe) across x, b and f for daily vmtest runs

curtin: add daily vmtest-f. stripe scheduling with b and x

---

cloud-init/centos.yaml

Changes:
- do not export PYVER as now only Python 3 is supported
- build the source RPM on CentOS 8
- use the workspace-cleanup wrapper instead of 'rm -rf'

copr: build using Python 3 and CentOS 8

---

curtin/jobs-ci.yaml

Keep 10 curtin-ci builds, up from the 3 we are keeping by default. One
build is about 26MB big, so we can easily afford to keep 10.

curtin-ci: keep 7 days of job results, up to 40 jobs 

---

git-ubuntu/jobs-ci.yaml

The branch can also be a tag, in this case the tag is checked-out in
detached head mode.

git-ubuntu-ci-nightly: parametrize the branch to test

---

cloud-init/integration-ec2.yaml

Number 8 in the day of the week field does not make sense and it's
ignored by Jenkins.

cloud-init-integration-ec2-f: fix the the timed trigger

---

curtin/default.yaml
curtin/jobs-vmtest-daily.yaml
curtin/jobs-vmtest-proposed.yaml

With vmtests we want to make sure to avoid overloading our CI infrastructure, so cron jobs need to be scheduled on different days.
This schedule 'striping' is especially important for curtin vmtests because the load is so heavy and test runs are so long. 
- Add a vmtest groovy job for curtin to get once weekly CI coverage on the 6th day of the week.
- Adjust curtin-vmtest-daily-f dropping this 3rd test schedule from days 2,5,6 to just 2,5
- Add a proposed vmtest for focal (so that vmtests can run against what cloud-init has uploaded
to the -proposed pocket for automated SRU verification into focal.

curtin: add vmtest jobs for proposed-focal and daily for groovy

---

metrics/default.yaml

A timeout of 30 minutes should good to prevent stuck jobs from being
unnoticed without killing occasionally slow jobs.
Closes #125

metrics: timestamp the builds and add a timeout

---

cloud-init/other.yaml

cloud-init commit a99c8bcea597c17d83d90bf1e09c9a5b68c3dc22 replaced the
tip-pycodestyle and tip-pyflakes tox environments with the tip-flake8
environment. This adapts the cloud-init-style-tip job to the change.

cloud-init tip jobs: fix the tox environments

---

daily-triage/tableflip-triage-email.sh

Add James and Lucas to the Wed schedule. 
Rotate them on even/odd weeks as well as for Monday rotation. 
Mondays are meant for James and Lucas to sort out since it'll always be every 4th week and consistently be even (this week is 29 and next week would be their rotation and week 30, then 34, etc).

Add JamesLucas to the bug triage rotation

---

curtin/jobs-vmtest-daily.yaml
curtin/jobs-vmtest-proposed.yaml

This assumes the ubuntu-minimal-daily remote is correctly setup on the
Jenkins nodes. This is done by running:
lxc remote add --protocol simplestreams ubuntu-minimal-daily \
https://cloud-images.ubuntu.com/minimal/daily/
The jenkins-slave-setup Ansible playbook takes care of this, and also
sets up the ubuntu-minimal remote for released images.

curtin: make curtainer use ubuntu-minimal images

---

cloud-init/centos.yaml
cloud-init/default.yaml

Test the copr build on centos 8 instead of centos 7. We are not even
building for centos 7 anymore due to missing Python 3 dependencies.

Test the COPR build on CentOS 8

---

ubuntu-advantage-client/default.yaml
ubuntu-advantage-client/jobs.yaml
ubuntu-advantage-client/parameters.yaml

Running the full set of uaclient test in travis CI is taking a lot of time (around 2h30), we want to move some of these tests to a daily jenkins job.
We are starting by moving the vm tests, which are currently not been run on travis due to time concerns as well. We will move other test in the near future.
PS: We cannot merge this branch until this [PR](https://github.com/canonical/ubuntu-advantage-client/pull/1204) lands in uaclient, since it sets some necessary definitions for vm tests to run

Add vm jobs to ubuntu-advantange-client

---

admin/deploy.yaml

Add a parameter to optionally make JJB delete the jobs it used to manage
but doesn't manage anymore (obsolete jobs, see [1]). Useful when Ubuntu
releases reach EOL and several jobs are to be removed at the same time.
Also: make JJB run on all the jobs directories even if it fails running
in one directory. In this case report failure on exit.
[1] https://docs.openstack.org/infra/jenkins-job-builder/execution.html#deleting-jobs-views

admin-jobs-update: support passing --delete-all to JJB

---

jenkins-jobs/admin/deploy.yaml
jenkins-jobs/admin/parameters.yaml

Allows easier testing of new job definition before submitting PRs.

deploy: allow to specify location and jobs to deploy

---

jenkins-jobs/ubuntu-advantage-client/jobs.yaml

If the uaclient jobs fail to execute, they may leave
stale lxd vms that do not need to persist in the node.
We are now adding a script to cleanup those stale vms

Add job to cleanup stale lxd vms

---

jenkins-jobs/ubuntu-advantage-client/default.yaml
jenkins-jobs/ubuntu-advantage-client/jobs.yaml

Add two jobs related to gcp in Jenkins. We are now introducing behave tests for generic gcp instances
and also a cleanup script to teardown instances that may not be deleted on the behave tests

Add uaclient gcp test job to Jenkins

---

jenkins-jobs/ubuntu-advantage-client/jobs.yaml

Xenial and Bionic GCP generic jobs require the staging token to run, but we are not binding this credential in the job definition.

Add staging token to gcpgeneric jobs

---

jenkins-jobs/ubuntu-advantage-client/jobs.yaml

We are now using new credentials to run our gcp uaclient jobs, because of that, we need to change the project id we are using on those jobs

Change project id value on gcp uaclient jobs

---

jenkins-jobs/git-ubuntu/jobs-ci.yaml

Commits 9fe8ea8, e79a3bc and fcfea1d are working well, so update the
nightly CI job the same way. This fixes the nightly CI job to work
correctly against the snapcraft core20 base that is now in master.

git-ubuntu: update nightly job to match MP CI

---

jenkins-jobs/oci/unit.yaml

- oci: skip the lts tests for non-lts packages
- oci unit: set AWS_PROFILE to allow logging in to public.ecr.aws

oci: update namespaces and provide aws region

---

jenkins-jobs/oci/unit.yaml

When manually triggering the job this change will allow to chose the registry to pull the image from.

oci unit: add 'choice' parameter to chose the registry

---

jenkins-jobs/git-ubuntu/jobs-ci.yaml

If an MP submitter has a tag in their repo that collides with a tag in our main repo, then `git fetch --tags` against our main repo fails. We need the main repo tags to help `git describe` generate a suitable version string for the built snap. We don't need the submitter's tags at all, so we can just avoid fetching their tags and this avoids the issue.

Handle tag conflicts in git-ubuntu MPs

---

jenkins-jobs/oci/unit.yaml

- oci: use the aws ecr creds when pulling images for the unit tests
- oci unit: set AWS_PROFILE according to DOCKER_NAMESPACE

OCI: use ecr creds to pull images for the unit tests

---

jenkins-jobs/cloud-init/other.yaml

True upstream for clout-init is GitHub.

cloud-init-style-tip: clone from GitHub and not from the LP mirror
